---
title: "SIMPlex_BC_FF_Spatial_qc"
author: "Mengxiao"
date: "2024-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r package, message='hide', results='hold'}
suppressMessages(require(semla))
suppressMessages(require(patchwork))
suppressMessages(require(ggplot2))
suppressMessages(require(ggpubr))
suppressMessages(require(tidyr))
```

## Load data

```{r loaddata}
# Load BC Visium samples
visium.dir <- 'spatial/BC_1'

samples <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'filtered_feature_bc_matrix.h5')

imgs <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_hires_image.png')

spotfiles <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_positions.csv')

json <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'scalefactors_json.json')

section.name <- samples
section.name <- gsub(paste0(visium.dir, "/"),"", gsub("/filtered_feature_bc_matrix.h5", "", section.name))

infoTable <- tibble(section.name, samples, imgs, spotfiles, json, # Add required columns
                    sample_id = c("BC_1.1", "BC_1.2")) # Add additional column

se <- ReadVisiumData(infoTable, verbose = FALSE)
```

## QC

```{r qc_featureplot}
feature.plot <- MapFeaturesSummary(se, features = "nFeature_Spatial", ncol = 2, subplot_type = "histogram", pt_stroke = NA)
count.plot <- MapFeaturesSummary(se, features = "nCount_Spatial", ncol = 2, subplot_type = "histogram", pt_stroke = NA)
feature.plot / count.plot
```

## Vln and scatters plots for QC

```{r vlnplotnew}
se$percent.mt <- PercentageFeatureSet(se, pattern = "^MT-")
se$percent.ribo <- PercentageFeatureSet(se, pattern = "^RPL|^RPS")
vln.plot <- VlnPlot(se, features = c("nFeature_Spatial", "nCount_Spatial", "percent.mt"), ncol = 3, group.by = "sample_id", pt.size = 0)
histo.plot <- ggplot() + 
  geom_histogram(data = se[[]], aes(nFeature_Spatial), fill = "red", alpha = 0.7, bins = 100) +
  ggtitle("Unique genes per spot") + geom_vline(xintercept = 500, color = "black", linetype = "dashed")
vln.plot / histo.plot

#Scatterplot
gene_attr <- do.call(rbind, lapply(unique(se$sample_id), function(i) {
  umis <- GetAssayData(se, slot = "counts", assay = "Spatial")[, se$sample_id %in% i]
  gene_attr <- data.frame(gene = rownames(umis),
                        counts = Matrix::rowSums(umis), 
                        det_rate = Matrix::rowMeans(umis > 0),
                        dataset = i)
}))
gene_attr$log10_count <- log10(gene_attr$counts + 1)

Log10counts <- spread(data = gene_attr[, c(1, 4, 5)], key = "dataset", value = "log10_count")
DetRate <- spread(data = gene_attr[, c(1, 3, 4)], key = "dataset", value = "det_rate")

p1 <- ggplot(Log10counts, aes(x=BC_1.1, y=BC_1.2)) + 
  geom_point()+
  geom_smooth(method=lm)+
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01)+
  labs(title="Log_10 counts")

p2 <- ggplot(DetRate, aes(x=BC_1.1, y=BC_1.2)) + 
  geom_point()+
  geom_smooth(method=lm)+
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01)+
  labs(title="Detection rate")

p1 - p2
```

## Session info
```{r session_info}
sessionInfo()
```

