---
title: "SIMPlex BC FF DE"
output: html_document
date: "2024-01-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r package, message='hide',warning='hide',results='hold'}
suppressMessages(require(Seurat))
suppressMessages(require(Matrix))
suppressMessages(require(tidyverse))
suppressMessages(require(patchwork))
suppressMessages(require(ggplot2))
suppressMessages(require(DoubletFinder))
suppressMessages(require(scCustomize))
```

## Load data

```{r loaddata}
# Load FF BC samples
snBC <- readRDS(file = "breast_cancer/FF_snRNA.rds")
```

## Cluster dotplot

```{r clusterdotplot, fig.height=20, fig.width=10}
Idents(snBC) <- snBC$manual_annot_0.5

markers_0.5_30 <- read.csv(file = "FF_BC/top30_markers_0.5.csv", row.names = FALSE)

markers_0.5_30$cluster[markers_0.5_30$cluster == "0"] <- "Cancer epithelial 1"
markers_0.5_30$cluster[markers_0.5_30$cluster == "1"] <- "Cancer epithelial 2"
markers_0.5_30$cluster[markers_0.5_30$cluster == "2"] <- "CAF 1"
markers_0.5_30$cluster[markers_0.5_30$cluster == "3"] <- "Cancer epithelial 3"
markers_0.5_30$cluster[markers_0.5_30$cluster == "4"] <- "TAM 1"
markers_0.5_30$cluster[markers_0.5_30$cluster == "5"] <- "Cancer epithelial 4"
markers_0.5_30$cluster[markers_0.5_30$cluster == "6"] <- "Immune cells/granulocytes"
markers_0.5_30$cluster[markers_0.5_30$cluster == "7"] <- "CAF 2"
markers_0.5_30$cluster[markers_0.5_30$cluster == "8"] <- "Endothelial cells"
markers_0.5_30$cluster[markers_0.5_30$cluster == "9"] <- "Cancer epithelial 5"
markers_0.5_30$cluster[markers_0.5_30$cluster == "10"] <- "Cancer proliferative"
markers_0.5_30$cluster[markers_0.5_30$cluster == "11"] <- "Vascular smooth muscle"
markers_0.5_30$cluster[markers_0.5_30$cluster == "12"] <- "Luminal epithelial cells"
markers_0.5_30$cluster[markers_0.5_30$cluster == "13"] <- "Basal epithelial cells"
markers_0.5_30$cluster[markers_0.5_30$cluster == "14"] <- "T cells"
markers_0.5_30$cluster[markers_0.5_30$cluster == "15"] <- "TAM 2"
markers_0.5_30$cluster[markers_0.5_30$cluster == "16"] <- "Immune cells/interferon-stimulated"

bc_top5 <- markers_0.5_30 %>%
  group_by(cluster) %>%
  arrange(cluster) %>%
  top_n(wt = avg_log2FC, n = 5)

DotPlot(snBC, 
        features = unique(bc_top5$gene), 
        col.min = 0, 
        dot.min = 0, 
        dot.scale = 5,
        group.by = "manual_annot_0.5") +
  RotatedAxis() + 
  xlab('Marker genes') + 
  ylab('Samples') + 
  scale_y_discrete(limits=rev) + 
  scale_x_discrete(position = "top") + 
  theme(text = element_text(size = 10), 
        axis.text.x=element_text(size=14),
        axis.text.x.top = element_text(margin = margin(b = 1), hjust = 0),
        axis.text.y=element_text(size=12), 
        legend.direction="horizontal", 
        legend.position = "top",
        plot.margin = margin(t = 20, r = 20, b = 20, l = 20, unit = "pt"))
```

## Session info
```{r session_info}
sessionInfo()
```
