---
title: "SIMPlex_FFPE_Spatial_B"
author: "Mengxiao"
date: "2024-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r package, message='hide', results='hold'}
suppressMessages(require(semla))
suppressMessages(require(patchwork))
suppressMessages(require(RcppML))
suppressMessages(require(ggplot2))
suppressMessages(require(singlet))
```

## Load data

```{r loaddata,message=FALSE, warning=FALSE, results='hold'}
# Load BC Visium samples
visium.dir <- 'BC/FFPE/spatial/patient_B'

samples <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'filtered_feature_bc_matrix.h5')

imgs <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_hires_image.png')

spotfiles <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_positions.csv')

json <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'scalefactors_json.json')

section.name <- samples
section.name <- gsub(paste0(visium.dir, "/"),"", gsub("/filtered_feature_bc_matrix.h5", "", section.name))

infoTable <- tibble(section.name, samples, imgs, spotfiles, json, # Add required columns
                    sample_id = c("FFPE BC 2")) # Add additional column

se <- ReadVisiumData(infoTable, verbose = FALSE)
```

## Filter by number of unique genes

```{r filtering}
# Filter by spots containing more than 500 genes and genes with more than 300 UMIs as well as at least 5 spots
nCount.UMI <- Matrix::rowSums(GetAssayData(se))
spatial.genes <- Matrix::rowSums(GetAssayData(se) > 0)
gene.data <- data.frame(nCounts = nCount.UMI, spatial.genes = spatial.genes)
min_expr <- gene.data$nCounts >= 300
min_obs <- gene.data$spatial.genes >= 5
keep.genes <- rownames(se)[min_expr & min_obs]
se_filtered <- SubsetSTData(se, features = keep.genes, expression = nFeature_Spatial > 500)
rm(se)
```

## Spatial clustering

```{r spatial_nmf}
DefaultAssay(se_filtered) <- "Spatial"

# Normalize data and find variable features for Visium data
se_filtered <- se_filtered |> 
  NormalizeData(verbose = FALSE) |>
  FindVariableFeatures(nfeatures = 10000, verbose = FALSE)

se_filtered <- RunNMF(se_filtered, verbose = FALSE)

MapFeatures(se_filtered, ncol = 5,
            features = paste0("NMF_", 1:20),
            override_plot_dims = TRUE, pt_stroke = NA,
            colors = viridis::magma(n = 11, direction = -1)) &
  theme(plot.title = element_blank())
```

## Import SIMPlex snRNAseq data
```{r import_sn}
snBC_FFPE_2 <- readRDS("BC/FFPE/FFPE_snRNA_Patient_B.rds")
Idents(snBC_FFPE_2) <- snBC_FFPE_2$manual_annot_0.8
```

## Normalize data and find variable features

```{r norm}
# Rerun FindVariableFeatures to increase the number before cell type deconvolution
snBC_FFPE_2 <- snBC_FFPE_2 |> 
  FindVariableFeatures(nfeatures = 10000, verbose = FALSE)
```

## Deconvolution with NNLS using 0.8 res annotations
```{r decon}
se_snBC_FFPE_B_NNLS <- RunNNLS(object = se_filtered, 
                            singlecell_object = snBC_FFPE_2,
                            groups = "manual_annot_0.8", nCells_per_group = 1000)
```

## Plot cell types 0.8 res annotations

```{r cell_type_plot}
DefaultAssay(se_snBC_FFPE_B_NNLS) <- "celltypeprops"

se_snBC_FFPE_B_NNLS <- LoadImages(se_snBC_FFPE_2_NNLS, verbose = FALSE, image_height = 2000)

selected_celltypes.2 <- c("Cancer epithelial 1 (ER-positive cancer 1)",
                          "Cancer epithelial 2",
                          "Cancer epithelial 3",
                          "Cancer epithelial 4",
                          "TAM",
                          "Luminal epithelial cells",
                          "CAF",
                          "Cancer epithelial 5 (ER-positive cancer 2)",
                          "Pericytes",
                          "T cells",
                          "Endothelial cells",
                          "Smooth muscle cells",
                          "Basal epithelial cells",
                          "Cancer epithelial 6 (Cancer undergoing EMT)",
                          "B cells")

MapFeatures(se_snBC_FFPE_B_NNLS, pt_size = 1.3, 
            features = selected_celltypes.2, image_use = "raw",
            override_plot_dims = TRUE,
            colors = RColorBrewer::brewer.pal(n = 9, name = "Blues"), 
            scale_alpha = TRUE) & 
  theme(legend.position = "right",
        legend.text = element_text(angle = 0),
        plot.title = element_blank())
```

## Multiple cell types
```{r multi_cell_type_plot}
# Plot multiple features
MapMultipleFeatures(se_snBC_FFPE_B_NNLS, 
                    image_use = "raw", 
                    pt_size = 2, max_cutoff = 0.99,
                    override_plot_dims = TRUE, 
                    colors = c("#F8766D", "#E58700", "#C99800", "#A3A500", "#6BB100", "#00BA38", "#00BF7D", "#00C0AF", "#00BCD8", "#00B0F6", "#619CFF", "#B983FF", "#E76BF3", "#FD61D1", "#FF67A4"),
                    features = selected_celltypes.2[1:15]) +
  plot_layout(guides = "collect")
```

## Save objects

```{r save}
saveRDS(se_snBC_FFPE_B_NNLS, file = "SIMPlex_BC_FFPE/spatial_bc_ffpe_B_NNLS.rds")
```

## Session info
```{r session_info}
sessionInfo()
```

