---
title: "SIMPlex_FFPE_A_Spatial"
author: "Mengxiao"
date: "2024-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r package, message='hide', results='hold'}
suppressMessages(require(semla))
suppressMessages(require(patchwork))
suppressMessages(require(RcppML))
suppressMessages(require(ggplot2))
suppressMessages(require(singlet))
```

## Load data

```{r loaddata}
# Load BC Visium samples
visium.dir <- 'BC/FFPE/spatial/patient_A'

samples <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'filtered_feature_bc_matrix.h5')

imgs <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_hires_image.png')

spotfiles <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'tissue_positions.csv')

json <- list.files(visium.dir, recursive = TRUE, full.names = TRUE, pattern = 'scalefactors_json.json')

section.name <- samples
section.name <- gsub(paste0(visium.dir, "/"),"", gsub("/filtered_feature_bc_matrix.h5", "", section.name))

infoTable <- tibble(section.name, samples, imgs, spotfiles, json, # Add required columns
                    sample_id = c("FFPE BC 1")) # Add additional column

se <- ReadVisiumData(infoTable, verbose = FALSE)
```

## Filter by number of unique genes

```{r filtering}
# Filter by spots containing more than 500 genes and genes with more than 300 UMIs as well as at least 5 spots
nCount.UMI <- Matrix::rowSums(GetAssayData(se))
spatial.genes <- Matrix::rowSums(GetAssayData(se) > 0)
gene.data <- data.frame(nCounts = nCount.UMI, spatial.genes = spatial.genes)
min_expr <- gene.data$nCounts >= 300
min_obs <- gene.data$spatial.genes >= 5
keep.genes <- rownames(se)[min_expr & min_obs]
se_filtered <- SubsetSTData(se, features = keep.genes, expression = nFeature_Spatial > 500)
rm(se)
```

## Spatial clustering

```{r spatial_nmf}
DefaultAssay(se_filtered) <- "Spatial"

# Normalize data and find variable features for Visium data
se_filtered <- se_filtered |> 
  NormalizeData(verbose = FALSE) |>
  FindVariableFeatures(nfeatures = 10000, verbose = FALSE)

se_filtered <- RunNMF(se_filtered, verbose = FALSE)

MapFeatures(se_filtered, ncol = 5,
            features = paste0("NMF_", 1:18),
            override_plot_dims = TRUE, pt_stroke = NA,
            colors = viridis::magma(n = 11, direction = -1)) &
  theme(plot.title = element_blank())
```

## Import SIMPlex snRNAseq data
```{r import_sn}
snBC_FFPE_1 <- readRDS("BC/FFPE/FFPE_snRNA_Patient_A.rds")
Idents(snBC_FFPE_1) <- snBC_FFPE_1$manual_annot_0.8
```

## Normalize data and find variable features

```{r norm}
# Rerun FindVariableFeatures to increase the number before cell type deconvolution
snBC_FFPE_1 <- snBC_FFPE_1 |> 
  FindVariableFeatures(nfeatures = 10000, verbose = FALSE)
```

## Deconvolution with NNLS using 0.8 res annotations

```{r decon}
se_snBC_FFPE_A_NNLS <- RunNNLS(object = se_snBC_FFPE_1, 
                               singlecell_object = snBC_FFPE_1, 
                               groups = "manual_annot_0.8", nCells_per_group = 1000)
```

## Plot cell types 0.8 res annotations

```{r cell_type_plot, fig.height=8, fig.width=12, message=FALSE, echo=FALSE, results='hide'}
DefaultAssay(se_snBC_FFPE_A_NNLS) <- "celltypeprops"

se_snBC_FFPE_A_NNLS <- LoadImages(se_snBC_FFPE_A_NNLS, verbose = FALSE, image_height = 2000)

selected_celltypes.1 <- c("CAF 1",
                          "Cancer epithelial 1",
                          "Cancer epithelial 2",
                          "Cancer epithelial 3",
                          "Stroma",
                          "Cancer epithelial 4",
                          "TAM",
                          "CAF 2",
                          "Cancer epithelial 5",
                          "Endothelial cells",
                          "T cells",
                          "Myoepithelial cells",
                          "Luminal epithelial cells",
                          "Fibroblasts",
                          "B cells")

MapFeatures(se_snBC_FFPE_A_NNLS, pt_size = 1.3, 
            features = selected_celltypes.1, image_use = "raw",
            override_plot_dims = TRUE,
            colors = RColorBrewer::brewer.pal(n = 9, name = "Blues"), 
            scale_alpha = TRUE) & 
  theme(legend.position = "right",
        legend.text = element_text(angle = 0), 
        plot.title = element_blank())
```

## Multiple cell types
```{r multi_cell_type_plot, fig.height=8, fig.width=11, message=FALSE, echo=FALSE, results='hide'}
# Plot multiple features
MapMultipleFeatures(se_snBC_FFPE_A_NNLS, 
                    image_use = "raw", 
                    pt_size = 2, max_cutoff = 0.99,
                    override_plot_dims = TRUE, 
                    colors = c("#F8766D", "#E58700", "#C99800", "#A3A500", "#6BB100", "#00BA38", "#00BF7D", "#00C0AF", "#00BCD8", "#00B0F6", "#619CFF", "#B983FF", "#E76BF3", "#FD61D1", "#FF67A4"),
                    features = selected_celltypes.1[1:15]) +
  plot_layout(guides = "collect")
```

## Save objects

```{r save, warning=FALSE, eval=FALSE}
saveRDS(se_snBC_FFPE_A_NNLS, file = "SIMPlex_BC_FFPE/spatial_bc_ffpe_A_NNLS.rds")
```

## Session info
```{r session_info}
sessionInfo()
```

